import { StyleSheet } from 'react-native';
import { theme } from '../theme';
import { type AppPalette, type AppTypography } from '../design';

export function createStyles(palette: AppPalette, typography: AppTypography) {
  return StyleSheet.create({
    safeArea: {
      flex: 1,
    },
    appShell: {
      flex: 1,
      backgroundColor: palette.background,
    },
    screenTransition: {
      flex: 1,
    },
    placeholder: {
      color: palette.muted,
    },
    sliderTint: {
      color: palette.primarySolid,
    },
    sliderTrack: {
      color: palette.outline,
    },
    backgroundGlowOne: {
      position: 'absolute',
      top: -120,
      right: -40,
      width: 240,
      height: 240,
      borderRadius: 120,
      backgroundColor: palette.glowOne,
    },
    backgroundGlowTwo: {
      position: 'absolute',
      top: 160,
      left: -80,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: palette.glowTwo,
    },
    backgroundGlowThree: {
      position: 'absolute',
      bottom: 120,
      right: -30,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: palette.glowThree,
    },
    screen: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.md,
      paddingBottom: 244,
      gap: theme.spacing.md,
    },
    stickyHeaderWrap: {
      paddingBottom: theme.spacing.xs,
      backgroundColor: palette.background,
      zIndex: 40,
      elevation: 40,
    },
    headerFrame: {
      backgroundColor: 'transparent',
    },
    headerShell: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      paddingLeft: theme.spacing.sm,
      paddingRight: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      borderRadius: 26,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
      elevation: 12,
    },
    headerSide: {
      minWidth: 42,
    },
    headerTextWrap: {
      flex: 1,
      minWidth: 0,
      paddingRight: theme.spacing.sm,
      alignItems: 'flex-start',
    },
    headerTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 26,
      lineHeight: 30,
      fontWeight: '700',
    },
    headerActionRow: {
      flexDirection: 'row',
      gap: 10,
      marginLeft: 'auto',
    },
    headerIconButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    headerIconButtonActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    headerIconGlyph: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 18,
      fontWeight: '700',
    },
    headerIconGlyphActive: {
      color: palette.foreground,
    },
    hero: {
      minHeight: 470,
      borderRadius: 34,
      overflow: 'hidden',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceHigh,
    },
    heroImage: {
      resizeMode: 'cover',
    },
    heroShade: {
      ...StyleSheet.absoluteFill,
      backgroundColor:
        palette.blurTint === 'dark'
          ? 'rgba(10, 8, 6, 0.42)'
          : 'rgba(10, 8, 6, 0.34)',
    },
    heroTextScrim: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: '72%',
      backgroundColor:
        palette.blurTint === 'dark'
          ? 'rgba(0, 0, 0, 0.2)'
          : 'rgba(0, 0, 0, 0.24)',
    },
    heroTopRow: {
      padding: theme.spacing.lg,
      alignItems: 'flex-end',
    },
    floatingBook: {
      width: 140,
      height: 120,
    },
    bookStackBack: {
      position: 'absolute',
      top: 16,
      left: 10,
      right: 0,
      bottom: 0,
      borderRadius: 26,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    bookStackFront: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 12,
      bottom: 16,
      borderRadius: 26,
      backgroundColor: palette.surfaceHigh,
      borderWidth: 1,
      borderColor: palette.outline,
      padding: theme.spacing.md,
      justifyContent: 'space-between',
    },
    bookStackTitle: {
      color: '#2d241a',
      fontFamily: typography.reading,
      fontSize: 24,
      fontWeight: '700',
    },
    bookStackMeta: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 1.3,
    },
    heroContent: {
      padding: theme.spacing.xl,
      gap: theme.spacing.sm,
    },
    heroEyebrow: {
      color: '#f1c96d',
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.3,
    },
    heroTitle: {
      color: '#fff8ea',
      fontFamily: typography.reading,
      fontSize: 39,
      lineHeight: 44,
      fontWeight: '700',
      maxWidth: 320,
    },
    heroDescription: {
      color: '#fff8ea',
      fontFamily: typography.reading,
      fontSize: 17,
      lineHeight: 27,
      maxWidth: 330,
    },
    heroStatsRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 4,
    },
    statCard: {
      flex: 1,
      borderRadius: 20,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: 'rgba(255, 250, 239, 0.84)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.34)',
      gap: 2,
    },
    statValue: {
      color: '#2d241a',
      fontFamily: typography.ui,
      fontSize: 21,
      fontWeight: '700',
    },
    statLabel: {
      color: '#6a5844',
      fontFamily: typography.ui,
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    heroButtonRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.sm,
      marginTop: theme.spacing.xs,
    },
    glassCard: {
      backgroundColor: palette.surfaceLowest,
      borderRadius: 30,
      padding: theme.spacing.lg,
      gap: theme.spacing.sm,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.16,
      shadowRadius: 28,
      elevation: 8,
    },
    sectionHeader: {
      gap: 4,
    },
    sectionTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 28,
      lineHeight: 32,
      fontWeight: '700',
    },
    screenTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 33,
      lineHeight: 37,
      fontWeight: '700',
    },
    lessonTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 31,
      lineHeight: 37,
      fontWeight: '700',
    },
    eyebrow: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.3,
      textTransform: 'uppercase',
    },
    bodyMuted: {
      color: palette.mutedStrong,
      fontFamily: typography.reading,
      fontSize: 16,
      lineHeight: 25,
    },
    helperText: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 13,
      lineHeight: 19,
    },
    listCard: {
      flexDirection: 'row',
      gap: theme.spacing.md,
      alignItems: 'flex-start',
      borderRadius: 24,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    listCardIcon: {
      width: 64,
      height: 64,
      borderRadius: 18,
      backgroundColor: palette.primaryContainer,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 6,
    },
    listCardIconText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 15,
      lineHeight: 18,
      fontWeight: '700',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    listCardBody: {
      flex: 1,
      gap: 4,
    },
    seriesCard: {
      borderRadius: 24,
      padding: theme.spacing.lg,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 5,
    },
    cardMeta: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
    },
    cardTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 23,
      lineHeight: 28,
      fontWeight: '600',
    },
    segmentedRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    segmentButton: {
      flex: 1,
      minWidth: 96,
      minHeight: 68,
      paddingVertical: 13,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    segmentButtonActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    segmentButtonText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
      lineHeight: 18,
      textAlign: 'center',
    },
    segmentButtonTextActive: {
      color: palette.foreground,
    },
    languageDropdownWrap: {
      gap: 8,
    },
    languageDropdownButton: {
      minHeight: 68,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderRadius: 22,
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.primary,
    },
    languageDropdownTextWrap: {
      flex: 1,
      minWidth: 0,
      gap: 3,
    },
    languageDropdownLabel: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    languageDropdownValue: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 21,
      lineHeight: 26,
      fontWeight: '700',
    },
    languageDropdownChevron: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 26,
      fontWeight: '900',
      marginLeft: 12,
    },
    languageDropdownMenu: {
      overflow: 'hidden',
      borderRadius: 22,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    languageDropdownOption: {
      minHeight: 58,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 10,
      paddingHorizontal: 14,
      borderBottomWidth: 1,
      borderBottomColor: palette.outlineVariant,
    },
    languageDropdownOptionActive: {
      backgroundColor: palette.primaryContainer,
    },
    languageDropdownOptionTextWrap: {
      flex: 1,
      minWidth: 0,
      gap: 2,
    },
    languageDropdownOptionNative: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 17,
      lineHeight: 23,
      fontWeight: '700',
    },
    languageDropdownOptionNativeActive: {
      color: palette.foreground,
    },
    languageDropdownOptionLabel: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    languageDropdownCheck: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 18,
      fontWeight: '900',
      marginLeft: 10,
    },
    infoChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    infoChipText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '600',
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
      marginTop: theme.spacing.xs,
    },
    toolbarRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.sm,
      marginTop: theme.spacing.xs,
    },
    primaryButton: {
      paddingHorizontal: 18,
      paddingVertical: 13,
      borderRadius: 999,
      backgroundColor: palette.primarySolid,
    },
    primaryButtonText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    secondaryButton: {
      paddingHorizontal: 18,
      paddingVertical: 13,
      borderRadius: 999,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    secondaryButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryButtonSpinner: {
      marginRight: 8,
    },
    secondaryButtonText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    audioErrorText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    searchWrap: {
      backgroundColor: palette.surfaceLowest,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 14,
    },
    searchInput: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      paddingVertical: 14,
    },
    loadingStateRow: {
      minHeight: 86,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: theme.spacing.sm,
    },
    searchResultCard: {
      gap: 8,
      borderRadius: 18,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    searchResultHighlight: {
      color: palette.foreground,
      backgroundColor: palette.primarySolid,
      fontFamily: typography.ui,
      fontWeight: '900',
    },
    sliderSection: {
      gap: 12,
    },
    sliderHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sliderLabel: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      fontWeight: '700',
    },
    sliderValue: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    sliderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    stepButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    stepButtonText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 20,
      fontWeight: '700',
    },
    slider: {
      flex: 1,
      height: 32,
    },
    fontChoiceGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    fontChoiceCard: {
      width: '31%',
      minWidth: 96,
      borderRadius: 22,
      paddingVertical: 16,
      paddingHorizontal: 10,
      alignItems: 'center',
      gap: 6,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    fontChoiceCardActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    fontChoiceSample: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 30,
    },
    fontChoiceLabel: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
    },
    previewLanguageRow: {
      flexDirection: 'row',
      marginTop: 2,
    },
    previewLanguageLabel: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    settingsPreviewHeading: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 22,
      fontWeight: '700',
    },
    settingsPreview: {
      color: palette.foreground,
      fontFamily: typography.reading,
    },
    summaryStatGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    summaryStatCard: {
      flex: 1,
      minWidth: 90,
      borderRadius: 18,
      paddingVertical: 14,
      paddingHorizontal: 12,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 2,
    },
    summaryStatValue: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 20,
      fontWeight: '700',
    },
    summaryStatLabel: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '600',
    },
    noteInput: {
      minHeight: 160,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceLow,
      padding: theme.spacing.md,
      color: palette.foreground,
      fontSize: 16,
      lineHeight: 24,
      fontFamily: typography.reading,
    },
    navigationRow: {
      flexDirection: 'row',
      gap: theme.spacing.md,
    },
    navigationColumn: {
      flex: 1,
      gap: theme.spacing.xs,
    },
    navLabel: {
      color: palette.muted,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
    },
    navLinkCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceLow,
      padding: theme.spacing.md,
    },
    navigationButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 72,
    },
    navigationButtonDisabled: {
      opacity: 0.45,
    },
    navLinkText: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600',
      textAlign: 'center',
    },
    resumePromptWrap: {
      position: 'absolute',
      right: theme.spacing.md,
      top: 142,
      zIndex: 3,
      pointerEvents: 'box-none',
    },
    resumePromptCard: {
      maxWidth: 154,
      borderRadius: 22,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.primary,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.16,
      shadowRadius: 18,
      elevation: 5,
    },
    resumePromptTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    resumePromptMeta: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 2,
    },
    savedStickyTabsWrap: {
      gap: 10,
      paddingVertical: theme.spacing.sm,
      backgroundColor: 'transparent',
      zIndex: 2,
      elevation: 2,
    },
    savedTabRow: {
      flexDirection: 'row',
      gap: 8,
      padding: 6,
      borderRadius: 22,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    savedTabButton: {
      flex: 1,
      minWidth: 0,
      minHeight: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 17,
      paddingHorizontal: 8,
      backgroundColor: 'transparent',
    },
    savedTabButtonActive: {
      backgroundColor: palette.primarySolid,
    },
    savedTabText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '800',
    },
    savedTabTextActive: {
      color: palette.onPrimary,
    },
    highlightFilterRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 2,
    },
    highlightFilterButton: {
      minHeight: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
      paddingHorizontal: 14,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    highlightFilterButtonActive: {
      borderColor: palette.primary,
      backgroundColor: palette.primaryContainer,
    },
    highlightFilterAllButton: {
      marginRight: 12,
    },
    highlightFilterText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '800',
    },
    highlightFilterTextActive: {
      color: palette.foreground,
    },
    highlightColorButton: {
      width: 38,
      height: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 19,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    highlightColorSwatch: {
      width: 24,
      height: 24,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: 'rgba(0,0,0,0.18)',
    },
    savedInsightCard: {
      borderRadius: 22,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 6,
    },
    savedInsightTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      fontWeight: '700',
    },
    savedInsightText: {
      color: palette.mutedStrong,
      fontFamily: typography.reading,
      fontSize: 15,
      lineHeight: 23,
    },
    savedHighlightSnippet: {
      alignSelf: 'flex-start',
      overflow: 'hidden',
      borderRadius: 8,
      paddingHorizontal: 6,
      paddingVertical: 2,
      color: '#201a15',
    },
    mediaCollectionHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    mediaCollectionTitleWrap: {
      flex: 1,
      gap: 4,
    },
    mediaCountBadge: {
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    mediaCountBadgeText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    noticeStack: {
      gap: 10,
    },
    noticeCard: {
      borderRadius: 22,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 5,
    },
    noticeTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    noticeText: {
      color: palette.mutedStrong,
      fontFamily: typography.reading,
      fontSize: 14,
      lineHeight: 21,
    },
    audioTrackCard: {
      borderRadius: 24,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 8,
    },
    audioTrackTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    audioTrackReferenceBadge: {
      borderRadius: 999,
      backgroundColor: palette.surfaceHigh,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    audioTrackReferenceText: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    audioTrackExtension: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    mediaCardActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
      marginTop: theme.spacing.xs,
    },
    mediaIconActionRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginLeft: 'auto',
    },
    mediaIconButton: {
      width: 46,
      height: 46,
      borderRadius: 23,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 14,
      elevation: 4,
    },
    mediaIconButtonActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    mediaIconButtonLoading: {
      backgroundColor: palette.surfaceHigh,
      borderColor: palette.primarySolid,
      borderWidth: 2,
    },
    mediaDownloadIcon: {
      width: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mediaDownloadStem: {
      width: 3,
      height: 12,
      borderRadius: 2,
      backgroundColor: palette.foreground,
      marginTop: 1,
    },
    mediaDownloadArrowHead: {
      width: 11,
      height: 11,
      borderRightWidth: 3,
      borderBottomWidth: 3,
      borderColor: palette.foreground,
      transform: [{ rotate: '45deg' }],
      marginTop: -8,
    },
    mediaDownloadTray: {
      width: 18,
      height: 3,
      borderRadius: 2,
      backgroundColor: palette.foreground,
      marginTop: 5,
    },
    mediaTrashIcon: {
      width: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mediaTrashLid: {
      width: 16,
      height: 3,
      borderRadius: 2,
      backgroundColor: palette.foreground,
      marginBottom: 2,
    },
    mediaTrashCan: {
      width: 15,
      height: 16,
      borderRadius: 3,
      borderWidth: 2,
      borderTopWidth: 0,
      borderColor: palette.foreground,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 3,
      paddingTop: 3,
    },
    mediaTrashLine: {
      width: 2,
      height: 9,
      borderRadius: 1,
      backgroundColor: palette.foreground,
      opacity: 0.78,
    },
    mediaIconPieceActive: {
      backgroundColor: palette.primarySolid,
      borderColor: palette.primarySolid,
    },
    mediaShareIcon: {
      width: 22,
      height: 22,
    },
    mediaShareDot: {
      position: 'absolute',
      width: 7,
      height: 7,
      borderRadius: 4,
      backgroundColor: palette.foreground,
    },
    mediaShareDotTop: {
      top: 2,
      right: 2,
    },
    mediaShareDotLeft: {
      left: 2,
      top: 9,
    },
    mediaShareDotRight: {
      right: 2,
      bottom: 2,
    },
    mediaShareLine: {
      position: 'absolute',
      width: 13,
      height: 2,
      borderRadius: 1,
      backgroundColor: palette.foreground,
      left: 6,
    },
    mediaShareLineTop: {
      top: 8,
      transform: [{ rotate: '-24deg' }],
    },
    mediaShareLineBottom: {
      bottom: 7,
      transform: [{ rotate: '25deg' }],
    },
    audioDownloadSpinner: {
      position: 'absolute',
      width: 40,
      height: 40,
    },
    audioDownloadProgressText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 9,
      fontWeight: '900',
    },
    audioTrackFileName: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '600',
    },
    audioTrackPath: {
      color: palette.muted,
      fontFamily: typography.ui,
      fontSize: 12,
      lineHeight: 18,
    },
    videoCard: {
      borderRadius: 26,
      overflow: 'hidden',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    videoThumbnailWrap: {
      height: 210,
      backgroundColor: palette.surfaceHigh,
    },
    videoThumbnail: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    videoThumbnailOverlay: {
      ...StyleSheet.absoluteFill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(10, 14, 24, 0.22)',
    },
    videoPlayButton: {
      borderRadius: 999,
      paddingHorizontal: 24,
      paddingVertical: 12,
      backgroundColor: 'rgba(255,255,255,0.88)',
    },
    videoPlayButtonText: {
      color: '#0e1726',
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    videoCardBody: {
      padding: theme.spacing.md,
      gap: 10,
    },
    videoMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
    },
    audioTransportCard: {
      borderRadius: 22,
      padding: 10,
      backgroundColor: palette.surfaceHigh,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 8,
    },
    audioTransportTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    audioTransportState: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    audioTransportTime: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '600',
    },
    audioTransportSlider: {
      width: '100%',
      height: 28,
    },
    audioTransportControls: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      gap: 4,
      justifyContent: 'center',
    },
    playbackSpeedRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    playbackSpeedButton: {
      flexGrow: 1,
      minWidth: 64,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 36,
      borderRadius: 14,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 8,
    },
    playbackSpeedButtonActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    playbackSpeedText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '800',
    },
    playbackSpeedTextActive: {
      color: palette.foreground,
    },
    playbackSpeedControl: {
      gap: 4,
    },
    playbackSpeedHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    playbackSpeedAdjustRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    playbackSpeedTextOnDark: {
      color: 'rgba(255,255,255,0.78)',
    },
    playbackSpeedCycleButton: {
      minWidth: 56,
      minHeight: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 17,
      backgroundColor: palette.primarySolid,
      paddingHorizontal: 10,
    },
    playbackSpeedCycleText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '900',
    },
    playbackSpeedSlider: {
      flex: 1,
      height: 30,
    },
    playbackSpeedScaleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: -8,
    },
    playbackSpeedScaleText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '700',
    },
    audioFullscreenButton: {
      minHeight: 42,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 999,
      backgroundColor: palette.primarySolid,
      paddingHorizontal: theme.spacing.md,
    },
    audioFullscreenButtonText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '800',
    },
    transportButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    transportButtonPrimary: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: palette.primarySolid,
      borderColor: palette.primarySolid,
    },
    transportButtonText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 16,
      fontWeight: '700',
    },
    transportButtonTextPrimary: {
      color: palette.onPrimary,
    },
    transportIconWrap: {
      minHeight: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    transportIconWrapReverse: {
      flexDirection: 'row-reverse',
    },
    transportPlayTriangle: {
      width: 0,
      height: 0,
      borderTopWidth: 8,
      borderBottomWidth: 8,
      borderLeftWidth: 13,
      borderTopColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: palette.foreground,
      marginLeft: 3,
    },
    transportPlayTrianglePrimary: {
      borderLeftColor: palette.onPrimary,
    },
    transportPauseWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    transportPauseBar: {
      width: 4,
      height: 15,
      borderRadius: 2,
      backgroundColor: palette.foreground,
    },
    transportPauseBarPrimary: {
      backgroundColor: palette.onPrimary,
    },
    transportSkipBar: {
      width: 3,
      height: 15,
      borderRadius: 2,
      backgroundColor: palette.foreground,
      marginRight: 2,
    },
    transportSkipTriangle: {
      width: 0,
      height: 0,
      borderTopWidth: 6,
      borderBottomWidth: 6,
      borderLeftWidth: 8,
      borderTopColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: palette.foreground,
    },
    transportSkipTrianglePrimary: {
      borderLeftColor: palette.onPrimary,
    },
    transportSkipTriangleTight: {
      marginLeft: -3,
    },
    transportSeekWrap: {
      minHeight: 18,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 0,
    },
    transportSeekGlyph: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '900',
      lineHeight: 14,
    },
    transportSeekValue: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 10,
      fontWeight: '900',
      lineHeight: 11,
      marginTop: -1,
    },
    videoModalSafeArea: {
      flex: 1,
      backgroundColor: '#000000',
    },
    videoModalCloseText: {
      color: '#ffffff',
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    videoModalPlayerWrap: {
      flex: 1,
      backgroundColor: '#000000',
    },
    videoModalContent: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: theme.spacing.md,
      gap: theme.spacing.md,
    },
    videoModalIframeFrame: {
      overflow: 'hidden',
      backgroundColor: '#000000',
      borderRadius: 14,
    },
    videoModalTitle: {
      alignSelf: 'stretch',
      color: '#ffffff',
      fontFamily: typography.reading,
      fontSize: 19,
      lineHeight: 24,
      fontWeight: '700',
      textAlign: 'center',
      paddingHorizontal: theme.spacing.xl,
    },
    videoModalError: {
      alignSelf: 'stretch',
      color: '#ffb4a9',
      fontFamily: typography.ui,
      fontSize: 14,
      lineHeight: 20,
      fontWeight: '700',
      textAlign: 'center',
      paddingHorizontal: theme.spacing.xl,
    },
    videoModalCloseButtonFloating: {
      position: 'absolute',
      top: theme.spacing.lg,
      right: theme.spacing.lg,
      zIndex: 3,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.16)',
      backgroundColor: 'rgba(16,16,16,0.55)',
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    videoModalPlayer: {
      flex: 1,
      backgroundColor: '#000000',
    },
    audioFullscreenSafeArea: {
      flex: 1,
      backgroundColor: '#070707',
    },
    audioFullscreenScroll: {
      flex: 1,
    },
    audioFullscreenScrollContent: {
      flexGrow: 1,
      padding: 10,
      paddingBottom: 18,
    },
    audioFullscreenCard: {
      flexGrow: 1,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.22)',
      backgroundColor: '#101010',
      paddingHorizontal: 14,
      paddingVertical: 12,
      alignItems: 'center',
      gap: 8,
    },
    audioFullscreenHeader: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    audioFullscreenEyebrow: {
      color: 'rgba(255,255,255,0.78)',
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 2,
    },
    audioFullscreenCloseButton: {
      width: 36,
      height: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
    },
    audioFullscreenCloseText: {
      color: '#ffffff',
      fontFamily: typography.ui,
      fontSize: 28,
      lineHeight: 30,
      fontWeight: '300',
    },
    audioArtwork: {
      width: 180,
      maxWidth: '60%',
      aspectRatio: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
      backgroundColor:
        palette.blurTint === 'dark' ? palette.primaryContainer : palette.primarySolid,
      shadowColor: '#000000',
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.28,
      shadowRadius: 28,
      elevation: 8,
    },
    audioArtworkText: {
      color: '#ffffff',
      fontFamily: typography.reading,
      fontSize: 40,
      fontWeight: '800',
    },
    audioFullscreenMeta: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 2.4,
      marginTop: 2,
    },
    audioFullscreenTitle: {
      color: '#ffffff',
      fontFamily: typography.reading,
      fontSize: 20,
      lineHeight: 25,
      fontWeight: '800',
      textAlign: 'center',
    },
    audioFullscreenProgress: {
      width: '100%',
      height: 26,
      marginTop: 0,
    },
    audioFullscreenTimeRow: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: -8,
    },
    audioFullscreenTime: {
      color: 'rgba(255,255,255,0.78)',
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '600',
    },
    audioFullscreenTransportRow: {
      width: '72%',
      maxWidth: 260,
      minHeight: 48,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 10,
      marginVertical: 0,
    },
    audioFullscreenSpeedCard: {
      width: '100%',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.26)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      padding: 10,
      gap: 6,
    },
    audioFullscreenSpeedTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.md,
    },
    audioFullscreenSpeedValue: {
      color: '#ffffff',
      fontFamily: typography.reading,
      fontSize: 28,
      lineHeight: 31,
      fontWeight: '800',
      marginTop: 8,
    },
    audioFullscreenSpeedIcon: {
      width: 44,
      height: 44,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.primarySolid,
    },
    audioFullscreenSpeedIconText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 24,
      fontWeight: '800',
    },
    audioFullscreenSpeedButtonRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    audioFullscreenSpeedButton: {
      minWidth: 54,
      minHeight: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 17,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.28)',
      backgroundColor: 'rgba(255,255,255,0.04)',
      paddingHorizontal: 12,
    },
    audioFullscreenSpeedButtonActive: {
      borderColor: palette.primarySolid,
      backgroundColor: palette.primarySolid,
    },
    audioFullscreenSpeedButtonText: {
      color: 'rgba(255,255,255,0.84)',
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '800',
    },
    audioFullscreenSpeedButtonTextActive: {
      color: palette.onPrimary,
    },
    audioFullscreenRateSlider: {
      width: '100%',
      height: 30,
    },
    audioFullscreenRateLabels: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: -6,
    },
    centeredScreen: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: theme.spacing.xl,
      gap: theme.spacing.sm,
      paddingBottom: 90,
    },
    bottomTabsShell: {
      position: 'absolute',
      left: theme.spacing.lg,
      right: theme.spacing.lg,
      bottom: 0,
      borderRadius: 999,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.24,
      shadowRadius: 32,
      elevation: 10,
      backgroundColor:
        palette.blurTint === 'dark'
          ? '#362d24'
          : palette.blurTint === 'light'
          ? '#fffaf0'
          : '#fff6e9',
    },
    miniPlayerShell: {
      position: 'absolute',
      left: theme.spacing.lg,
      right: theme.spacing.lg,
      bottom: 106,
      zIndex: 4,
    },
    miniPlayerFabShell: {
      position: 'absolute',
      right: theme.spacing.lg,
      zIndex: 4,
    },
    miniPlayerFab: {
      width: 62,
      height: 62,
      borderRadius: 31,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.primarySolid,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.24)',
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.26,
      shadowRadius: 22,
      elevation: 10,
    },
    miniPlayerFabText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 28,
      fontWeight: '900',
    },
    miniPlayerCard: {
      gap: theme.spacing.sm,
      borderRadius: 24,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: 14,
      backgroundColor:
        palette.blurTint === 'dark'
          ? '#40352b'
          : palette.blurTint === 'light'
          ? '#fffaf0'
          : '#fff6e9',
      borderWidth: 1,
      borderColor:
        palette.blurTint === 'dark'
          ? 'rgba(255,255,255,0.18)'
          : 'rgba(60,45,30,0.16)',
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.16,
      shadowRadius: 24,
      elevation: 8,
    },
    miniPlayerHeadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    miniPlayerTextWrap: {
      minWidth: 0,
      gap: 4,
    },
    miniPlayerEyebrow: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    miniPlayerTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 16,
      lineHeight: 21,
      fontWeight: '700',
    },
    miniPlayerMeta: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '600',
    },
    miniPlayerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    miniPlayerSpeedControl: {
      gap: 2,
    },
    miniPlayerSpeedHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    miniPlayerSpeedAdjustRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
    },
    miniPlayerSpeedText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '800',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    miniPlayerSpeedCycleButton: {
      minWidth: 54,
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 16,
      backgroundColor: palette.primarySolid,
      paddingHorizontal: 10,
    },
    miniPlayerSpeedCycleText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '900',
    },
    miniPlayerSpeedSlider: {
      flex: 1,
      height: 28,
    },
    miniPlayerActionButton: {
      borderRadius: 999,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 14,
      paddingVertical: 10,
      minWidth: 76,
      alignItems: 'center',
    },
    miniPlayerRoundButton: {
      width: 46,
      height: 46,
      minWidth: 46,
      paddingHorizontal: 0,
      paddingVertical: 0,
      justifyContent: 'center',
    },
    miniPlayerSeekButton: {
      borderRadius: 999,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      width: 46,
      height: 46,
      alignItems: 'center',
      justifyContent: 'center',
    },
    miniPlayerCloseButton: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    miniPlayerActionText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    bottomTabsBlur: {
      ...StyleSheet.absoluteFill,
    },
    bottomTabsContent: {
      flexDirection: 'row',
      padding: 6,
      minHeight: 74,
      position: 'relative',
      overflow: 'hidden',
      backgroundColor:
        palette.blurTint === 'dark'
          ? '#362d24'
          : palette.blurTint === 'light'
          ? '#fffaf0'
          : '#fff6e9',
    },
    tabActiveIndicatorShell: {
      position: 'absolute',
      top: 6,
      bottom: 6,
      left: 0,
      zIndex: 0,
    },
    tabActiveIndicatorTrailShell: {
      top: 9,
      bottom: 9,
    },
    tabActiveIndicator: {
      flex: 1,
      borderRadius: 999,
      backgroundColor: palette.primarySolid,
      shadowColor: palette.primarySolid,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.34,
      shadowRadius: 18,
      elevation: 8,
    },
    tabActiveIndicatorTrail: {
      flex: 1,
      borderRadius: 999,
      backgroundColor: palette.highlight,
    },
    tabButton: {
      flex: 1,
      paddingVertical: 6,
      paddingHorizontal: 2,
      borderRadius: 999,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
    },
    tabButtonContent: {
      alignItems: 'center',
      gap: 3,
    },
    tabIconFrame: {
      width: 26,
      height: 26,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabHomeIcon: {
      width: 22,
      height: 20,
      alignItems: 'center',
    },
    tabHomeRoof: {
      width: 0,
      height: 0,
      borderLeftWidth: 11,
      borderRightWidth: 11,
      borderBottomWidth: 9,
      borderLeftColor: 'transparent',
      borderRightColor: 'transparent',
    },
    tabHomeBody: {
      width: 16,
      height: 10,
      marginTop: -1,
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
    },
    tabOpenBookIcon: {
      width: 24,
      height: 22,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabOpenBookPage: {
      width: 11,
      height: 18,
      borderWidth: 2,
      borderTopLeftRadius: 4,
      borderTopRightRadius: 4,
      borderBottomLeftRadius: 2,
      borderBottomRightRadius: 2,
    },
    tabOpenBookLeftPage: {
      transform: [{ rotate: '-8deg' }],
      marginRight: -1,
    },
    tabOpenBookRightPage: {
      transform: [{ rotate: '8deg' }],
      marginLeft: -1,
    },
    tabAudioIcon: {
      width: 24,
      height: 22,
      alignItems: 'center',
      justifyContent: 'flex-end',
    },
    tabAudioHeadband: {
      position: 'absolute',
      top: 2,
      width: 20,
      height: 11,
      borderWidth: 2.5,
      borderBottomWidth: 0,
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
      backgroundColor: 'transparent',
    },
    tabAudioCupsRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      width: 22,
      marginTop: 8,
    },
    tabAudioEarCup: {
      width: 7,
      height: 10,
      borderRadius: 3,
    },
    tabVideoIcon: {
      width: 24,
      height: 16,
      borderRadius: 4,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabVideoPlayTriangle: {
      width: 0,
      height: 0,
      marginLeft: 2,
      borderTopWidth: 5,
      borderBottomWidth: 5,
      borderLeftWidth: 8,
      borderTopColor: 'transparent',
      borderBottomColor: 'transparent',
    },
    tabGearIcon: {
      width: 22,
      height: 22,
      alignItems: 'center',
      justifyContent: 'center',
    },
    tabGearTooth: {
      position: 'absolute',
      width: 3.5,
      height: 5.5,
      borderRadius: 1,
    },
    tabGearRing: {
      width: 14,
      height: 14,
      borderRadius: 7,
      borderWidth: 2.5,
      backgroundColor: 'transparent',
    },
    tabLabel: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '700',
    },
    tabLabelActive: {
      color: palette.onPrimary,
    },
    sheetOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.24)',
    },
    sheetBackdrop: {
      ...StyleSheet.absoluteFill,
    },
    sheetWrap: {
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceLowest,
    },
    sheetBlur: {
      ...StyleSheet.absoluteFill,
    },
    sheetContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingTop: 12,
      paddingBottom: 28,
      gap: 16,
      backgroundColor: palette.surfaceLowest,
    },
    sheetHandle: {
      alignSelf: 'center',
      width: 46,
      height: 5,
      borderRadius: 999,
      backgroundColor: palette.outline,
      marginBottom: 2,
    },
    sheetHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 20,
      fontWeight: '700',
    },
    sheetCloseButton: {
      paddingVertical: 6,
      paddingHorizontal: 10,
    },
    sheetCloseText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    inlineSection: {
      gap: 10,
    },
    inlineSectionTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      fontWeight: '700',
    },
    inlineFontRow: {
      gap: 10,
    },
    inlineFontChip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    inlineFontChipActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    inlineFontChipText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    fullSettingsButton: {
      marginTop: 4,
      paddingVertical: 14,
      borderRadius: 18,
      alignItems: 'center',
      backgroundColor: palette.primarySolid,
    },
    fullSettingsText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    selectionToolbar: {
      position: 'absolute',
      left: 8,
      right: 8,
      bottom: 88,
      zIndex: 20,
      elevation: 20,
      paddingHorizontal: 0,
      paddingBottom: 0,
    },
    selectionSheet: {
      borderWidth: 1,
      borderRadius: 16,
      padding: 10,
      gap: 8,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.22,
      shadowRadius: 24,
    },
    selectionSheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    selectionHeaderText: {
      flex: 1,
    },
    selectionTitle: {
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    selectionPreview: {
      fontFamily: typography.reading,
      fontSize: 12,
      marginTop: 3,
      lineHeight: 16,
    },
    selectionCloseButton: {
      paddingHorizontal: 8,
      paddingVertical: 6,
    },
    selectionCloseButtonText: {
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    selectionColorRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 7,
    },
    selectionColorSwatch: {
      width: 27,
      height: 27,
      borderRadius: 14,
      borderWidth: 2,
    },
    selectionActionGrid: {
      flexDirection: 'row',
      gap: 6,
    },
    selectionActionButton: {
      flex: 1,
      minHeight: 38,
      borderWidth: 1,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
      paddingVertical: 8,
    },
    selectionActionButtonText: {
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
  });
}

export type AppStyles = ReturnType<typeof createStyles>;
