import { Platform, StyleSheet } from 'react-native';
import { theme } from '../theme';
import { type AppPalette, type AppTypography } from '../design';

export function createStyles(palette: AppPalette, typography: AppTypography) {
  const systemFontFamily = Platform.select({
    ios: 'System',
    android: 'sans-serif',
    default: undefined,
  });

  return StyleSheet.create({
    safeArea: {
      flex: 1,
    },
    appShell: {
      flex: 1,
      backgroundColor: palette.background,
    },
    placeholder: {
      color: palette.muted,
    },
    sliderTint: {
      color: palette.primarySolid,
    },
    sliderTrack: {
      color: palette.outline,
    },
    backgroundGlowOne: {
      position: 'absolute',
      top: -120,
      right: -40,
      width: 240,
      height: 240,
      borderRadius: 120,
      backgroundColor: palette.glowOne,
    },
    backgroundGlowTwo: {
      position: 'absolute',
      top: 160,
      left: -80,
      width: 220,
      height: 220,
      borderRadius: 110,
      backgroundColor: palette.glowTwo,
    },
    backgroundGlowThree: {
      position: 'absolute',
      bottom: 120,
      right: -30,
      width: 180,
      height: 180,
      borderRadius: 90,
      backgroundColor: palette.glowThree,
    },
    screen: {
      flex: 1,
    },
    scrollContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingTop: theme.spacing.md,
      paddingBottom: 244,
      gap: theme.spacing.md,
    },
    stickyHeaderWrap: {
      paddingBottom: theme.spacing.xs,
      backgroundColor: palette.background,
    },
    headerFrame: {
      backgroundColor: 'transparent',
    },
    headerShell: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: theme.spacing.sm,
      paddingLeft: theme.spacing.sm,
      paddingRight: theme.spacing.sm,
      paddingVertical: theme.spacing.sm,
      borderRadius: 26,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.12,
      shadowRadius: 18,
      elevation: 0,
    },
    headerSide: {
      minWidth: 42,
    },
    headerTextWrap: {
      flex: 1,
      minWidth: 0,
      paddingRight: theme.spacing.sm,
      alignItems: 'flex-start',
    },
    headerTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 26,
      lineHeight: 30,
      fontWeight: '700',
    },
    headerActionRow: {
      flexDirection: 'row',
      gap: 10,
      marginLeft: 'auto',
    },
    headerIconButton: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    headerIconButtonActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    headerIconGlyph: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 18,
      fontWeight: '700',
    },
    headerIconGlyphActive: {
      color: palette.foreground,
    },
    hero: {
      minHeight: 470,
      borderRadius: 34,
      overflow: 'hidden',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceHigh,
    },
    heroImage: {
      resizeMode: 'cover',
    },
    heroShade: {
      ...StyleSheet.absoluteFill,
      backgroundColor:
        palette.blurTint === 'dark'
          ? 'rgba(10, 8, 6, 0.42)'
          : 'rgba(10, 8, 6, 0.34)',
    },
    heroTextScrim: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      height: '72%',
      backgroundColor:
        palette.blurTint === 'dark'
          ? 'rgba(0, 0, 0, 0.2)'
          : 'rgba(0, 0, 0, 0.24)',
    },
    heroTopRow: {
      padding: theme.spacing.lg,
      alignItems: 'flex-end',
    },
    floatingBook: {
      width: 140,
      height: 120,
    },
    bookStackBack: {
      position: 'absolute',
      top: 16,
      left: 10,
      right: 0,
      bottom: 0,
      borderRadius: 26,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    bookStackFront: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 12,
      bottom: 16,
      borderRadius: 26,
      backgroundColor: palette.surfaceHigh,
      borderWidth: 1,
      borderColor: palette.outline,
      padding: theme.spacing.md,
      justifyContent: 'space-between',
    },
    bookStackTitle: {
      color: '#2d241a',
      fontFamily: typography.reading,
      fontSize: 24,
      fontWeight: '700',
    },
    bookStackMeta: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 1.3,
    },
    heroContent: {
      padding: theme.spacing.xl,
      gap: theme.spacing.sm,
    },
    heroEyebrow: {
      color: '#f1c96d',
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.3,
    },
    heroTitle: {
      color: '#fff8ea',
      fontFamily: typography.reading,
      fontSize: 39,
      lineHeight: 44,
      fontWeight: '700',
      maxWidth: 320,
    },
    heroDescription: {
      color: '#fff8ea',
      fontFamily: typography.reading,
      fontSize: 17,
      lineHeight: 27,
      maxWidth: 330,
    },
    heroStatsRow: {
      flexDirection: 'row',
      gap: 10,
      marginTop: 4,
    },
    statCard: {
      flex: 1,
      borderRadius: 20,
      paddingVertical: 12,
      paddingHorizontal: 14,
      backgroundColor: 'rgba(255, 250, 239, 0.84)',
      borderWidth: 1,
      borderColor: 'rgba(255, 255, 255, 0.34)',
      gap: 2,
    },
    statValue: {
      color: '#2d241a',
      fontFamily: typography.ui,
      fontSize: 21,
      fontWeight: '700',
    },
    statLabel: {
      color: '#6a5844',
      fontFamily: typography.ui,
      fontSize: 11,
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    heroButtonRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.sm,
      marginTop: theme.spacing.xs,
    },
    glassCard: {
      backgroundColor: palette.surfaceLowest,
      borderRadius: 30,
      padding: theme.spacing.lg,
      gap: theme.spacing.sm,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 18 },
      shadowOpacity: 0.16,
      shadowRadius: 28,
      elevation: 8,
    },
    sectionHeader: {
      gap: 4,
    },
    sectionTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 28,
      lineHeight: 32,
      fontWeight: '700',
    },
    screenTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 33,
      lineHeight: 37,
      fontWeight: '700',
    },
    lessonTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 31,
      lineHeight: 37,
      fontWeight: '700',
    },
    eyebrow: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 1.3,
      textTransform: 'uppercase',
    },
    bodyMuted: {
      color: palette.mutedStrong,
      fontFamily: typography.reading,
      fontSize: 16,
      lineHeight: 25,
    },
    helperText: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 13,
      lineHeight: 19,
    },
    listCard: {
      flexDirection: 'row',
      gap: theme.spacing.md,
      alignItems: 'flex-start',
      borderRadius: 24,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    listCardIcon: {
      width: 64,
      height: 64,
      borderRadius: 18,
      backgroundColor: palette.primaryContainer,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 6,
    },
    listCardIconText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 15,
      lineHeight: 18,
      fontWeight: '700',
      textAlign: 'center',
      textTransform: 'uppercase',
    },
    listCardBody: {
      flex: 1,
      gap: 4,
    },
    seriesCard: {
      borderRadius: 24,
      padding: theme.spacing.lg,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 5,
    },
    cardMeta: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 11,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
    },
    cardTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 23,
      lineHeight: 28,
      fontWeight: '600',
    },
    segmentedRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    segmentButton: {
      flex: 1,
      minWidth: 96,
      paddingVertical: 13,
      borderRadius: 18,
      alignItems: 'center',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    segmentButtonActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    segmentButtonText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    segmentButtonTextActive: {
      color: palette.foreground,
    },
    infoChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 999,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    infoChipText: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '600',
    },
    metaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
      marginTop: theme.spacing.xs,
    },
    toolbarRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.sm,
      marginTop: theme.spacing.xs,
    },
    primaryButton: {
      paddingHorizontal: 18,
      paddingVertical: 13,
      borderRadius: 999,
      backgroundColor: palette.primarySolid,
    },
    primaryButtonText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    secondaryButton: {
      paddingHorizontal: 18,
      paddingVertical: 13,
      borderRadius: 999,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    secondaryButtonContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryButtonSpinner: {
      marginRight: 8,
    },
    secondaryButtonText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    audioErrorText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    searchWrap: {
      backgroundColor: palette.surfaceLowest,
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 14,
    },
    searchInput: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      paddingVertical: 14,
    },
    sliderSection: {
      gap: 12,
    },
    sliderHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sliderLabel: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      fontWeight: '700',
    },
    sliderValue: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    sliderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    stepButton: {
      width: 36,
      height: 36,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    stepButtonText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 20,
      fontWeight: '700',
    },
    slider: {
      flex: 1,
      height: 32,
    },
    fontChoiceGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    fontChoiceCard: {
      width: '31%',
      minWidth: 96,
      borderRadius: 22,
      paddingVertical: 16,
      paddingHorizontal: 10,
      alignItems: 'center',
      gap: 6,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    fontChoiceCardActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    fontChoiceSample: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 30,
    },
    fontChoiceLabel: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textAlign: 'center',
    },
    settingsPreviewHeading: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 22,
      fontWeight: '700',
    },
    settingsPreview: {
      color: palette.foreground,
      fontFamily: typography.reading,
    },
    noteInput: {
      minHeight: 160,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceLow,
      padding: theme.spacing.md,
      color: palette.foreground,
      fontSize: 16,
      lineHeight: 24,
      fontFamily: typography.reading,
    },
    navigationRow: {
      flexDirection: 'row',
      gap: theme.spacing.md,
    },
    navigationColumn: {
      flex: 1,
      gap: theme.spacing.xs,
    },
    navLabel: {
      color: palette.muted,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.2,
    },
    navLinkCard: {
      borderRadius: 22,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceLow,
      padding: theme.spacing.md,
    },
    navigationButton: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      minHeight: 72,
    },
    navigationButtonDisabled: {
      opacity: 0.45,
    },
    navLinkText: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 18,
      lineHeight: 24,
      fontWeight: '600',
      textAlign: 'center',
    },
    resumePromptWrap: {
      position: 'absolute',
      right: theme.spacing.md,
      top: 142,
      zIndex: 3,
      pointerEvents: 'box-none',
    },
    resumePromptCard: {
      maxWidth: 154,
      borderRadius: 22,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: palette.primaryContainer,
      borderWidth: 1,
      borderColor: palette.primary,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.16,
      shadowRadius: 18,
      elevation: 5,
    },
    resumePromptTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    resumePromptMeta: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 2,
    },
    savedInsightCard: {
      borderRadius: 22,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 6,
    },
    savedInsightTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      fontWeight: '700',
    },
    savedInsightText: {
      color: palette.mutedStrong,
      fontFamily: typography.reading,
      fontSize: 15,
      lineHeight: 23,
    },
    mediaCollectionHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    mediaCollectionTitleWrap: {
      flex: 1,
      gap: 4,
    },
    mediaCountBadge: {
      borderRadius: 999,
      backgroundColor: palette.primaryContainer,
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    mediaCountBadgeText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    audioTrackCard: {
      borderRadius: 24,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 8,
    },
    audioTrackTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    audioTrackReferenceBadge: {
      borderRadius: 999,
      backgroundColor: palette.surfaceHigh,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    audioTrackReferenceText: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    audioTrackExtension: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    audioTrackFileName: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '600',
    },
    audioTrackPath: {
      color: palette.muted,
      fontFamily: typography.ui,
      fontSize: 12,
      lineHeight: 18,
    },
    videoCard: {
      borderRadius: 26,
      overflow: 'hidden',
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    videoThumbnailWrap: {
      height: 210,
      backgroundColor: palette.surfaceHigh,
    },
    videoThumbnail: {
      width: '100%',
      height: '100%',
      resizeMode: 'cover',
    },
    videoThumbnailOverlay: {
      ...StyleSheet.absoluteFill,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: 'rgba(10, 14, 24, 0.22)',
    },
    videoPlayButton: {
      borderRadius: 999,
      paddingHorizontal: 24,
      paddingVertical: 12,
      backgroundColor: 'rgba(255,255,255,0.88)',
    },
    videoPlayButtonText: {
      color: '#0e1726',
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1,
    },
    videoCardBody: {
      padding: theme.spacing.md,
      gap: 10,
    },
    videoMetaRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
    },
    audioTransportCard: {
      borderRadius: 22,
      padding: theme.spacing.md,
      backgroundColor: palette.surfaceHigh,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      gap: 10,
    },
    audioTransportTopRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    audioTransportState: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    audioTransportTime: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '600',
    },
    audioTransportSlider: {
      width: '100%',
      height: 28,
    },
    audioTransportControls: {
      flexDirection: 'row',
      flexWrap: 'nowrap',
      gap: 6,
      justifyContent: 'space-between',
    },
    transportButton: {
      flex: 1,
      minWidth: 0,
      paddingHorizontal: 8,
      paddingVertical: 10,
      borderRadius: 16,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    transportButtonPrimary: {
      backgroundColor: palette.primarySolid,
      borderColor: palette.primarySolid,
    },
    transportButtonText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 16,
      fontWeight: '700',
    },
    transportButtonTextPrimary: {
      color: palette.onPrimary,
    },
    transportIconWrap: {
      minHeight: 18,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    transportIconWrapReverse: {
      flexDirection: 'row-reverse',
    },
    transportPlayTriangle: {
      width: 0,
      height: 0,
      borderTopWidth: 10,
      borderBottomWidth: 10,
      borderLeftWidth: 16,
      borderTopColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: palette.foreground,
      marginLeft: 3,
    },
    transportPlayTrianglePrimary: {
      borderLeftColor: palette.onPrimary,
    },
    transportPauseWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    transportPauseBar: {
      width: 5,
      height: 18,
      borderRadius: 2,
      backgroundColor: palette.foreground,
    },
    transportPauseBarPrimary: {
      backgroundColor: palette.onPrimary,
    },
    transportSkipBar: {
      width: 4,
      height: 18,
      borderRadius: 2,
      backgroundColor: palette.foreground,
      marginRight: 2,
    },
    transportSkipTriangle: {
      width: 0,
      height: 0,
      borderTopWidth: 8,
      borderBottomWidth: 8,
      borderLeftWidth: 10,
      borderTopColor: 'transparent',
      borderBottomColor: 'transparent',
      borderLeftColor: palette.foreground,
    },
    transportSkipTrianglePrimary: {
      borderLeftColor: palette.onPrimary,
    },
    transportSkipTriangleTight: {
      marginLeft: -3,
    },
    transportSeekWrap: {
      minHeight: 18,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 0,
    },
    transportSeekGlyph: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '900',
      lineHeight: 14,
    },
    transportSeekValue: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 10,
      fontWeight: '900',
      lineHeight: 11,
      marginTop: -1,
    },
    videoModalSafeArea: {
      flex: 1,
      backgroundColor: '#000000',
    },
    videoModalCloseText: {
      color: '#ffffff',
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    videoModalPlayerWrap: {
      flex: 1,
      backgroundColor: '#000000',
    },
    videoModalCloseButtonFloating: {
      position: 'absolute',
      top: theme.spacing.lg,
      right: theme.spacing.lg,
      zIndex: 3,
      borderRadius: 999,
      borderWidth: 1,
      borderColor: 'rgba(255,255,255,0.16)',
      backgroundColor: 'rgba(16,16,16,0.55)',
      paddingHorizontal: 16,
      paddingVertical: 10,
    },
    videoModalPlayer: {
      flex: 1,
      backgroundColor: '#000000',
    },
    centeredScreen: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: theme.spacing.xl,
      gap: theme.spacing.sm,
      paddingBottom: 90,
    },
    bottomTabsShell: {
      position: 'absolute',
      left: theme.spacing.lg,
      right: theme.spacing.lg,
      bottom: theme.spacing.lg,
      borderRadius: 30,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.24,
      shadowRadius: 32,
      elevation: 10,
      backgroundColor:
        palette.blurTint === 'dark'
          ? '#362d24'
          : palette.blurTint === 'light'
          ? '#fffaf0'
          : '#fff6e9',
    },
    miniPlayerShell: {
      position: 'absolute',
      left: theme.spacing.lg,
      right: theme.spacing.lg,
      bottom: 126,
      zIndex: 4,
    },
    miniPlayerCard: {
      gap: theme.spacing.sm,
      borderRadius: 24,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: 14,
      backgroundColor:
        palette.blurTint === 'dark'
          ? '#40352b'
          : palette.blurTint === 'light'
          ? '#fffaf0'
          : '#fff6e9',
      borderWidth: 1,
      borderColor:
        palette.blurTint === 'dark'
          ? 'rgba(255,255,255,0.18)'
          : 'rgba(60,45,30,0.16)',
      shadowColor: palette.shadow,
      shadowOffset: { width: 0, height: 14 },
      shadowOpacity: 0.16,
      shadowRadius: 24,
      elevation: 8,
    },
    miniPlayerHeadingRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.sm,
    },
    miniPlayerTextWrap: {
      minWidth: 0,
      gap: 4,
    },
    miniPlayerEyebrow: {
      color: palette.primary,
      fontFamily: typography.ui,
      fontSize: 10,
      fontWeight: '700',
      textTransform: 'uppercase',
      letterSpacing: 1.1,
    },
    miniPlayerTitle: {
      color: palette.foreground,
      fontFamily: typography.reading,
      fontSize: 16,
      lineHeight: 21,
      fontWeight: '700',
    },
    miniPlayerMeta: {
      color: palette.mutedStrong,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '600',
    },
    miniPlayerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 8,
    },
    miniPlayerActionButton: {
      borderRadius: 999,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 14,
      paddingVertical: 10,
      minWidth: 76,
      alignItems: 'center',
    },
    miniPlayerSeekButton: {
      borderRadius: 999,
      backgroundColor: palette.surfaceLowest,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      paddingHorizontal: 14,
      paddingVertical: 10,
      minWidth: 64,
      alignItems: 'center',
    },
    miniPlayerCloseButton: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    miniPlayerActionText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
    bottomTabsBlur: {
      ...StyleSheet.absoluteFill,
    },
    bottomTabsContent: {
      flexDirection: 'row',
      padding: 8,
      backgroundColor:
        palette.blurTint === 'dark'
          ? '#362d24'
          : palette.blurTint === 'light'
          ? '#fffaf0'
          : '#fff6e9',
    },
    tabButton: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 4,
      borderRadius: 20,
      alignItems: 'center',
      gap: 3,
    },
    tabButtonActive: {
      backgroundColor: palette.primarySolid,
    },
    tabIcon: {
      color: palette.mutedStrong,
      fontFamily: systemFontFamily,
      fontSize: 18,
      fontWeight: '700',
    },
    tabIconActive: {
      color: palette.onPrimary,
    },
    tabLabel: {
      color: palette.mutedStrong,
      fontFamily: systemFontFamily,
      fontSize: 11,
      fontWeight: '700',
    },
    tabLabelActive: {
      color: palette.onPrimary,
    },
    sheetOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0,0,0,0.24)',
    },
    sheetBackdrop: {
      ...StyleSheet.absoluteFill,
    },
    sheetWrap: {
      borderTopLeftRadius: 30,
      borderTopRightRadius: 30,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: palette.outlineVariant,
      backgroundColor: palette.surfaceLowest,
    },
    sheetBlur: {
      ...StyleSheet.absoluteFill,
    },
    sheetContent: {
      paddingHorizontal: theme.spacing.lg,
      paddingTop: 12,
      paddingBottom: 28,
      gap: 16,
      backgroundColor: palette.surfaceLowest,
    },
    sheetHandle: {
      alignSelf: 'center',
      width: 46,
      height: 5,
      borderRadius: 999,
      backgroundColor: palette.outline,
      marginBottom: 2,
    },
    sheetHeaderRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    sheetTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 20,
      fontWeight: '700',
    },
    sheetCloseButton: {
      paddingVertical: 6,
      paddingHorizontal: 10,
    },
    sheetCloseText: {
      color: palette.primarySolid,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    inlineSection: {
      gap: 10,
    },
    inlineSectionTitle: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 15,
      fontWeight: '700',
    },
    inlineFontRow: {
      gap: 10,
    },
    inlineFontChip: {
      paddingHorizontal: 14,
      paddingVertical: 10,
      borderRadius: 999,
      backgroundColor: palette.surfaceLow,
      borderWidth: 1,
      borderColor: palette.outlineVariant,
    },
    inlineFontChipActive: {
      backgroundColor: palette.primaryContainer,
      borderColor: palette.primary,
    },
    inlineFontChipText: {
      color: palette.foreground,
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    fullSettingsButton: {
      marginTop: 4,
      paddingVertical: 14,
      borderRadius: 18,
      alignItems: 'center',
      backgroundColor: palette.primarySolid,
    },
    fullSettingsText: {
      color: palette.onPrimary,
      fontFamily: typography.ui,
      fontSize: 14,
      fontWeight: '700',
    },
    selectionToolbar: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 18,
      zIndex: 20,
      elevation: 20,
      paddingHorizontal: 16,
      paddingBottom: 14,
    },
    selectionSheet: {
      borderWidth: 1,
      borderRadius: 16,
      padding: 14,
      gap: 12,
      shadowOffset: { width: 0, height: 12 },
      shadowOpacity: 0.22,
      shadowRadius: 24,
    },
    selectionSheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    selectionHeaderText: {
      flex: 1,
    },
    selectionTitle: {
      fontFamily: typography.ui,
      fontSize: 15,
      fontWeight: '700',
    },
    selectionPreview: {
      fontFamily: typography.reading,
      fontSize: 13,
      marginTop: 3,
      lineHeight: 18,
    },
    selectionCloseButton: {
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    selectionCloseButtonText: {
      fontFamily: typography.ui,
      fontSize: 13,
      fontWeight: '700',
    },
    selectionColorRow: {
      flexDirection: 'row',
      gap: 10,
    },
    selectionColorSwatch: {
      width: 34,
      height: 34,
      borderRadius: 17,
      borderWidth: 3,
    },
    selectionActionGrid: {
      flexDirection: 'row',
      gap: 8,
    },
    selectionActionButton: {
      flex: 1,
      minHeight: 42,
      borderWidth: 1,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
      paddingVertical: 10,
    },
    selectionActionButtonText: {
      fontFamily: typography.ui,
      fontSize: 12,
      fontWeight: '700',
    },
  });
}

export type AppStyles = ReturnType<typeof createStyles>;
